name         'puppetlabs-designate'
version      '0.0.1'
author       'Xingchao Yu and StackForge Contributors'
license      'Apache License 2.0'
summary      'Puppet module for OpenStack Designate'
description  'Installs and configures OpenStack Designate (DNS Services).'
project_page 'https://launchpad.net/puppet-designate'
source       'https://github.com/stackforge/puppet-designate'

dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
dependency 'puppetlabs/mysql', '>=0.9.0 <3.0.0'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
